Ajuste SonarCloud + Readme

diff --git a/.github/workflows/ci-producao.yaml b/.github/workflows/ci-producao.yaml
--- a/.github/workflows/ci-producao.yaml
+++ b/.github/workflows/ci-producao.yaml
@@ -15,6 +15,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -32,7 +34,7 @@ jobs:
             exit 1
           fi
 
-          pip install pytest pytest-cov
+          pip install pytest pytest-cov coverage
 
       - name: Run tests
         env:
@@ -40,9 +42,24 @@ jobs:
           DATABASE_URL: "sqlite+pysqlite:///:memory:"
         run: |
           if [ -d tests ]; then
-            python -m pytest tests --cov=app --cov-report=xml:coverage.xml
+            python -m pytest
+            if [ ! -f coverage.xml ]; then
+              echo "coverage.xml NOT found"
+              ls -lah
+              exit 1
+            fi
           else
             echo "Pasta ./tests não encontrada."
+            exit 1
+          fi
+
+      - name: Verify coverage report
+        run: |
+          if [ -f coverage.xml ]; then
+            echo "coverage.xml found:"
+            ls -lah coverage.xml
+          else
+            echo "coverage.xml NOT found"
             exit 1
           fi
 
